POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4YWQ2Y2YyNGM3MzQ0OGZmMzNiY2U5ZCIsImlhdCI6MTc1NjIwMDk4NH0.akvVsnTKLbARQ0iQO_bnUmUxUMT9-AqX6s2IbsQMJl8

{
    "title": "Testing245678",
    "author": "N/A",
    "url": "http://localhost/",
    "likes": 666
}
